language: node_js
node_js:
  - "6"
before_script:
  - yarn add --force node-sass # https://github.com/yarnpkg/yarn/issues/1981
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gulp serve &
cache:
  yarn: true
  directories:
    - node_modules
sudo: false
